stages:
  - make_assets
  - embed_reveal
  - docusaurus

build_dir: /build
output_type: last
output_dir: /output

make_assets:
  plugin: command
  options:
    command: make
    locations:
      - chapters/binary-introduction/application-lifetime/slides
      - chapters/binary-introduction/assembly-language/slides
      - chapters/binary-introduction/binary-analysis/slides
      - chapters/binary-introduction/taming-the-stack/slides
      - chapters/binary-introduction/overview/slides
      - chapters/data/data-representation/slides
      - chapters/data/overview/slides
      - chapters/demystifying-web/explaining-the-internet/slides
      - chapters/demystifying-web/hacking-the-web/slides
      - chapters/demystifying-web/rediscovering-the-browser/slides
      - chapters/demystifying-web/overview/slides
      - chapters/scratch-linux/system-exploration/slides
      - chapters/scratch-linux/welcome-to-linux/slides
      - chapters/scratch-linux/overview/slides
    args:
      - all

embed_reveal:
  plugin: reveal_embed
  options:
    target: docusaurus
    extension: mdx
    build:
      assembly-language: assembly-language
      binary-analysis: binary-analysis
      taming-the-stack: taming-the-stack
      application-lifetime: application-lifetime
      data-representation: data-representation
      data-security: data-security
      explaining-the-internet: explaining-the-internet
      hacking-the-web: hacking-the-web
      rediscovering-the-browser: rediscovering-the-browser
      system-exploration: system-exploration
      welcome-to-linux: welcome-to-linux

docusaurus:
  plugin: docusaurus
  options:
    course_name: Essentials Security
    sidebar: js
    structure:
      - Scratch Linux:
          - Welcome to Linux:
              path: chapters/scratch-linux/welcome-to-linux/
              extra:
                - media/
              subsections:
                - Reading:
                    path: reading/
                    subsections:
                      - Introduction: introduction.md
                      - Working with Linux: working-with-linux.md
                      - Enter Python: enter-python.md
                      - Summary: summary.md
                      - Activities: activities.md
                      - Further Reading: further-reading.md
                - Drills:
                    path: drills/
                    subsections:
                      - Tasks:
                          path: tasks/
                          subsections:
                            - In Your Face/: in-your-face/README.md
                            - Did You Look Everywhere/: did-you-look-everywhere/README.md
                            - What is Running/: whats-running/README.md
                            - Quick Mafs/: quick-mafs/README.md
                            - Jumbled/: jumbled/README.md
          - System Exploration:
              path: chapters/scratch-linux/system-exploration/
              subsections:
                - Reading:
                    path: reading/
                    subsections:
                      - Introduction: introduction.md
                      - Exploration tools: exploration-tools.md
                      - File inspection: file-inspection.md
                      - Summary: summary.md
                      - Further reading: further-reading.md
                - Guides:
                    path: guides/
                    subsections:
                      - Doge: doge/README.md
                - Drills:
                    path: drills/
                    subsections:
                      - Tasks:
                          path: tasks/
                          subsections:
                          - Empty Files/: empty-files/README.md
                          - Find us if you can/: find-us-if-you-can/README.md
                          - Not your doge/: not-your-doge/README.md
                          - Surgical precision/: surgical-precision/README.md
      - Demystifying the Web:
          - Explaining the Internet:
              path: chapters/demystifying-web/explaining-the-internet/
              extra:
                - media/
              subsections:
                - Reading: reading/README.md
          - Re-Discovering the Browser:
              path: chapters/demystifying-web/rediscovering-the-browser/
              extra:
                - media/
              subsections:
                - Reading:
                    path: reading/
                    subsections:
                      - Introduction: introduction.md
                      - Triple A\'s: triple-a.md
                      - Hyper Text Transfer Protocol: http.md
                      - Browsers: browsers.md
                      - Summary: summary.md
                      - Further Reading: further-reading.md
                - Drills:
                    path: drills/
                    subsections:
                      - Tasks:
                          path: tasks/
                          subsections:
                            - Cockroach/: cockroach/README.md
                            - Give to Get/: give-to-get/README.md
                            - Eyes/: eyes/README.md
                            - Give to Post/: give-to-post/README.md
                            - King Kong/: king-kong/README.md
                            - Name/: name/README.md
                            - Gimme/: gimme/README.md
                            - Surprise/: surprise/README.md
                - Guides:
                    path: guides/
                    subsections:
                      - Readme/: readme/README.md
                      - One more Pinger/: one-more-pinger/README.md
          - Hacking the Web:
              path: chapters/demystifying-web/hacking-the-web/
              extra:
                - media/
              subsections:
                - Reading: reading/README.md
      - Data:
          - Data Representation:
              path: chapters/data/data-representation/
              subsections:
                - Reading: reading/README.md
          - Data Security:
              path: chapters/data/data-security/
              extra:
                - media/
              subsections:
                - Reading:
                    - Introduction: reading/introduction.md
                    - Exclusive Or (XOR): reading/xor-encrpytion.md
                    - Symmetric Cryptography: reading/symmetric-cryptography.md
                    - Asymmetric Cryptography: reading/asymmetric-cryptography.md
                - Drills:
                    path: drills/
                    subsections:
                      - Tasks:
                          path: tasks/
                          subsections:
                            - Caesar Cipher/: caesar-cipher/README.md
                            - Xor Encryption/: xor-encryption/README.md
                            - AES CBC/: aes-cbc/README.md

      - Binary Introduction:
          - Application Lifetime:
              path: chapters/binary-introduction/application-lifetime/
              extra:
                - media/
              subsections:
                - Reading: reading/README.md
          - Binary Analysis:
              path: chapters/binary-introduction/binary-analysis/
              subsections:
                - Reading: reading/README.md
          - Assembly Language:
              path: chapters/binary-introduction/assembly-language/
              extra:
                - media/
              subsections:
                  - Reading:
                      - Introduction: reading/introduction.md
                      - Registers: reading/registers.md
                      - Assembly Instructions: reading/assembly-instructions.md
                      - Dereferencing Addresses: reading/dereferencing-addresses.md
                      - Reading Assembly: reading/reading-assembly.md
                      - Summary: reading/summary.md
                      - Further Reading: reading/further-reading.md
                  - Drills:
                      - Tasks:
                          - In Plain Assembly/: drills/tasks/in-plain-assembly/README.md
                          - Gotta Link Em All/: drills/tasks/gotta-link-em-all/README.md
                          - Jump Maze/: drills/tasks/jump-maze/README.md
                          - Crypto/: drills/tasks/crypto/README.md
                          - Call Me Little Sunshine/: drills/tasks/call-me-little-sunshine/README.md
          - Taming the Stack:
              path: chapters/binary-introduction/taming-the-stack/
              subsections:
                - Reading: reading/README.md

    static_assets:
      - application-lifetime: /build/make_assets/chapters/binary-introduction/application-lifetime/slides/_site
      - assembly-language: /build/make_assets/chapters/binary-introduction/assembly-language/slides/_site
      - binary-analysis: /build/make_assets/chapters/binary-introduction/binary-analysis/slides/_site
      - taming-the-stack: /build/make_assets/chapters/binary-introduction/taming-the-stack/slides/_site

      - data-representation: /build/make_assets/chapters/data/data-representation/slides/_site

      - explaining-the-internet: /build/make_assets/chapters/demystifying-web/explaining-the-internet/slides/_site
      - hacking-the-web: /build/make_assets/chapters/demystifying-web/hacking-the-web/slides/_site
      - rediscovering-the-browser: /build/make_assets/chapters/demystifying-web/rediscovering-the-browser/slides/_site

      - welcome-to-linux: /build/make_assets/chapters/scratch-linux/welcome-to-linux/slides/_site
      - system-exploration: /build/make_assets/chapters/scratch-linux/system-exploration/slides/_site
    config_meta:
      title: Essentials Security
      url: http://localhost/
      baseUrl: /essentials-security/
      onBrokenLinks: warn
      onBrokenMarkdownLinks: warn
    config_socials:
      OCW: https://security.cs.pub.ro/summer-school/wiki/
      Facebook: https://www.facebook.com/SSSUPB/
    copyright_string: SSS Team
